from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    package_root = Path(__file__).resolve().parent.parent
    schema_path = package_root / "schema" / "flow.schema.json"
    output_path = package_root / "generated" / "flow_models.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    schema_version = schema["properties"]["schemaVersion"]["const"]
    node_types = schema["$defs"]["nodeType"]["enum"]
    node_type_literal = ", ".join([f'"{node_type}"' for node_type in node_types])

    source = f'''"""Auto-generated by scripts/generate_models.py. Do not edit manually."""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


FLOW_SCHEMA_VERSION = "{schema_version}"
NodeType = Literal[{node_type_literal}]
RunStatus = Literal["pending", "running", "success", "failed", "canceled"]
RunEventLevel = Literal["debug", "info", "warn", "error"]
FlowVariableValue = str | int | float | bool | None


class FlowNode(BaseModel):
    id: str
    type: NodeType
    label: str | None = None
    config: dict[str, Any] = Field(default_factory=dict)


class FlowEdge(BaseModel):
    id: str
    source: str
    target: str
    condition: str | None = None


class FlowModel(BaseModel):
    schemaVersion: str = FLOW_SCHEMA_VERSION
    id: str
    name: str
    variables: dict[str, FlowVariableValue] = Field(default_factory=dict)
    nodes: list[FlowNode]
    edges: list[FlowEdge]


class ValidateResponse(BaseModel):
    valid: bool
    errors: list[str] = Field(default_factory=list)


class ApiError(BaseModel):
    code: str
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    requestId: str


class RunEvent(BaseModel):
    eventId: str
    timestamp: str
    runId: str
    nodeId: str
    nodeType: NodeType
    level: RunEventLevel = "info"
    message: str
    durationMs: int | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class RunResult(BaseModel):
    runId: str
    flowId: str
    status: RunStatus
    startedAt: str
    finishedAt: str | None = None
    events: list[RunEvent] = Field(default_factory=list)
'''

    output_path.write_text(source, encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
