import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(__dirname, "..");
const schemaPath = resolve(packageRoot, "schema", "flow.schema.json");
const outputPath = resolve(packageRoot, "generated", "types.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf-8"));
const nodeTypes = schema?.$defs?.nodeType?.enum ?? [];
const schemaVersion = schema?.properties?.schemaVersion?.const ?? "1.0.0";

const nodeTypeUnion = nodeTypes.map(type => `'${type}'`).join(" | ");

const source = `/* eslint-disable */
// Auto-generated by scripts/generate-types.mjs. Do not edit manually.

export const FLOW_SCHEMA_VERSION = '${schemaVersion}' as const;

export type NodeType = ${nodeTypeUnion};
export type RunStatus = 'pending' | 'running' | 'success' | 'failed' | 'canceled';
export type RunEventLevel = 'debug' | 'info' | 'warn' | 'error';
export type FlowVariableValue = string | number | boolean | null;

export interface FlowNode {
  id: string;
  type: NodeType;
  label?: string;
  config: Record<string, unknown>;
}

export interface FlowEdge {
  id: string;
  source: string;
  target: string;
  condition?: string;
}

export interface FlowModel {
  schemaVersion: typeof FLOW_SCHEMA_VERSION;
  id: string;
  name: string;
  variables?: Record<string, FlowVariableValue>;
  nodes: FlowNode[];
  edges: FlowEdge[];
}

export interface ValidateResponse {
  valid: boolean;
  errors: string[];
}

export interface ApiError {
  code: string;
  message: string;
  details: Record<string, unknown>;
  requestId: string;
}

export interface RunEvent {
  eventId: string;
  timestamp: string;
  runId: string;
  nodeId: string;
  nodeType: NodeType;
  level: RunEventLevel;
  message: string;
  durationMs?: number;
  data?: Record<string, unknown>;
}

export interface RunResult {
  runId: string;
  flowId: string;
  status: RunStatus;
  startedAt: string;
  finishedAt?: string;
  events: RunEvent[];
}
`;

mkdirSync(resolve(packageRoot, "generated"), { recursive: true });
writeFileSync(outputPath, source, "utf-8");
console.log(`Generated ${outputPath}`);
